### ISSUE TITLE
js- префиксы

### ISSUE THREAD

**Issue by a-poluhin** [sodiqit/fsd-step-2#15]
По стандарту все выражения, которые используются для поиска по DOM, должны иметь префикс js-
![image](https://user-images.githubusercontent.com/10168007/92150438-9cdd6600-ee49-11ea-9e10-c604e0660d56.png)
Т.е. помимо обычно класса на элементе должен висеть другой класс с js- префексом.
![image](https://user-images.githubusercontent.com/10168007/92150470-a797fb00-ee49-11ea-9be3-b74aa1b39317.png)

**Comment by a-poluhin** [comment]
А зачем ты оставляешь 2 класс. Одна из причин добавления класса js-... классов, чтобы не использовать другие классы для выборки.
![image](https://user-images.githubusercontent.com/10168007/92616460-70fa2e80-f2e8-11ea-9d96-8f283f25a096.png)

**Comment by sodiqit** [comment]
Оставляю, потому что если понадобиться подключить несколько datepicker'ов (как например на странице cards, то будет некорректно осуществлять выборку), потому что будет несколько классов js-datepicker. Поэтому думаю здесь уместно оставить чтобы для choice room(и др.) выбрался нужный datepicker в любом случае.

**Comment by sodiqit** [comment]
Единственное место где остались такие классы так это в form elements, но это демонстрационная панелька, где куча одинаковых элементов и я думаю тут можно отступить от правила(так как легче искать множество элементов без добавления лишних классов и модификатор которые особо не нужны). По остальному полноценному сайту используется один класс.
