### ISSUE TITLE
Поле ввода даты

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#21]
Сейчас от маски есть только текст в плейсхолдере, а нужно, чтобы вводились только корректные даты в формате, который описан в плейсхолдере
![image](https://user-images.githubusercontent.com/46089168/94655835-db125c00-0307-11eb-8bb9-99fcb481b04a.png)

**Comment by Fr0stmourne** [comment]
Уже лучше, но даты валидные должны быть)
![image](https://user-images.githubusercontent.com/46089168/94944661-3d26b900-04e2-11eb-8a39-93efa98d5cbe.png)

**Comment by sodiqit** [comment]
Случайно ключевым словом закрылось ишью)
