### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#23]
- многоточие в случае переполнения лучше реализовать без JS, так как это создает дополнительную сложность, погугли про свойство text-overflow
- На мой взгляд, было бы удобнее, если бы форма выпадала при клике на любой участок этого блока, а не только на стрелочку
![image](https://user-images.githubusercontent.com/46089168/94657780-a358e380-030a-11eb-8cc0-464f068455a9.png)
- Нужно для удобства пользователей добавить обработчик, который закрывал бы форму при клике вне её

**Comment by sodiqit** [comment]
Возникла сложность с text-overflow. При добавлении этого свойства по началу кажется что все хорошо.
![image](https://user-images.githubusercontent.com/47000555/94931981-e325f380-04e1-11eb-8b70-ae7a4a88fca3.png)
Но так как у меня меняются склонения слов то может возникать такая проблема
![image](https://user-images.githubusercontent.com/47000555/94932329-5c254b00-04e2-11eb-9e9a-06aa0a153c2c.png)
Если немного расширю область чтобы вмещались слово "кроватей", то получается так
![image](https://user-images.githubusercontent.com/47000555/94932819-02715080-04e3-11eb-8161-aad588e1977c.png)
![image](https://user-images.githubusercontent.com/47000555/94932864-11f09980-04e3-11eb-8fdc-46a598050b62.png)
Мне кажется это не очень красиво, да и впринципе особой сложности нет при добавлении многоточия, добавляется всего 3 строчки, все равно исходная строка генерируется js-ом. Поэтому пока оставлю все как есть, можно будет обсудить в телеге если это сильно критичный момент =)

**Comment by Fr0stmourne** [comment]
Я глянул, как ты это реализовал, и советую тебе порефакторить вот этот кусок 
![image](https://user-images.githubusercontent.com/46089168/94946108-529ce280-04e4-11eb-9a0e-59bbaf8f1b06.png)

Очень сложно с ходу разобраться в такой вложенности, можно это же сделать гораздо проще, посмотри в сторону методов массива (map, join)

**Comment by Fr0stmourne** [comment]
А в целом мысль такая, что если можно функционал реализовать просто на css + html  и это буквально несколько строчек, зачастую это лучший способ, т.к. js добавляет сложности, как правило

**Comment by sodiqit** [comment]
да, понимаю. Просто здесь мне кажется лучше через js, так будет лучше, я посмотрю как улучшить фрагмент

**Comment by Fr0stmourne** [comment]
Еще в этих файлах дублируется логика для дропдауна (видимо для разных страниц, сильно не всматривался). Нужно добавить эту логику в одном месте в универсальный компонент, куда бы просто передавались пункты дропдауна (спальни, ванные комнаты и т.д.) и использовать его по всему проекту
![image](https://user-images.githubusercontent.com/46089168/94947094-c1c70680-04e5-11eb-960c-a9f4ad7d19a6.png)

**Comment by Fr0stmourne** [comment]
Нашел странную вещь, вроде и в файле dropdown.pug есть разметка, и в js-файле дропдауна есть очень похожая разметка в строке, и там, и там используется она?

**Comment by sodiqit** [comment]
Нет, просто паг файл позволяет без js внешний вид ui передать. Использовал его до того как написал плагин на js

**Comment by Fr0stmourne** [comment]
А зачем нужно держать разметку в js? по идее, ты можешь всю разметку нужную сгенерить в pug-файле, передав туда нужный контент, а js только для логики уже подключить

**Comment by sodiqit** [comment]
Так я js и так для логики и использую, потому чтобы не надо париться с именами, дата-атрибутами, чтобы поля сами рендерились в зависимости от переданных опций, а паг файл создал до js'a, могу конечно удалить, но он может быть как fallback некий. Просто если будет необходимость добавить новый пункт в какой либо dropdown то придется идти править пагфайл, а так можно будет передать просто
```javascript
const dropdown = new Dropdown(el, options);
// когда необходимо добавить новое поле 
dropdown.update(newOptions);
``` 
Или например будет какой нибудь fetch запрос где придут новые поля, чтобы не думать о разметке, просто метод вызвать и он перегенерирует уже новую разметку. А паг файл просто как fallback чтобы не развалился сайт при выключенном js'e. Мне кажется такой подход оптимальный и не нужно без конца бегать и править паг файлы.

**Comment by Fr0stmourne** [comment]
Я не совсем понимаю, почему нельзя без использования разметки в js файле добавить новые опции, достаточно же просто скопировать существующие ноды и в них поменять наполнение, разве нет? основная проблема разметки в 2 местах, что если потребуется её изменить, то надо не забыть сделать это сразу в 2 местах, это всегда создает дополнительные неудобства. По идее, тебе для генерации всего дропдауна должно быть достаточно разметки из pug-файла, ты из него можешь получить всё, что тебе нужно

**Comment by sodiqit** [comment]
Убрал всю неиспользуемую разметку из js'a
