### ISSUE TITLE
visually-hidden

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#24]
Пользователям скринридеров/читалок/... не нужно знать, что в начале страницы есть свг-спрайт, так что лучше скрыть это просто через `display: none;`
![image](https://user-images.githubusercontent.com/46089168/94658525-94266580-030b-11eb-926d-dfde3ec6560b.png)

**Comment by sodiqit** [comment]
Через display: none, не работают иконки, я их скрыл от скриридера через сочетание visibility и position
