### ISSUE TITLE
Кнопка со стрелкой

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#32]
Тут стрелка куда-то съехала, из-за этого фокус имеет странную форму)
![image](https://user-images.githubusercontent.com/46089168/94948370-e1f7c500-04e7-11eb-9255-86d883e8a6d5.png)
![image](https://user-images.githubusercontent.com/46089168/94948338-d2787c00-04e7-11eb-898d-166f0dfa0d98.png)

**Comment by sodiqit** [comment]
Поправил похоже пока правил другую ишью) Сейчас работает нормально

**Comment by Fr0stmourne** [comment]
Если задавать абсолютное позиционирование, то еще нужно добавлять отступы, иначе будет вот так при большом количестве текста)
![image](https://user-images.githubusercontent.com/46089168/95490862-84f58680-09a1-11eb-8a0a-fd639f5d074c.png)
