### ISSUE TITLE
Центрирование

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#33]
При таком варианте центрирования (скрины от радиокнопки), если придется изменить 12 пикселей, то надо еще не забыть записать половину от нового значения вместо 6 пикселей чуть ниже, чтобы все не съехало. Проще поддерживать такой подход:
```
left: 0;
top: 0;
transform: translate(-50%, -50%);
```

% в транслейте считаются тоже от самого элемента и править их не нужно будет)
![image](https://user-images.githubusercontent.com/46089168/94948643-4f0b5a80-04e8-11eb-83a9-47f2b32b7c3d.png)

**Comment by sodiqit** [comment]
Да, знаю такой подход, но там нужно сначала сдвинуть на 50% а только потом translate применять если 0 оставить то не по центру элемент будет.

**Comment by Fr0stmourne** [comment]
да, я тут опечатался)
