### ISSUE TITLE
Ширина в %

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/fsd-step-2#36]
Местами встречаются странные значения ширины, которые похожи на подгонку под pixelperfect, так относительные значения лучше не использовать. Если нужно точное значение - лучше использовать абсолютные величины
![image](https://user-images.githubusercontent.com/46089168/96036997-ecae4480-0e6d-11eb-8f4f-34f2a750d49f.png)

**Comment by sodiqit** [comment]
это не для точного значения и не для pp, а чтобы не городить лишние медиа выражения. Если выставить 100% то потом придется на разных разрешениях городить пару лишних медиа запросов и править там padding или margin. Зачем? А так всегда блок 80 процентов или 1160px еще и по центру(макета для мобилки и планшета нет). Вот только 1 процент да, там из за того что на экране, который равен 1440px не дотягивает чутка блок до 1160px. Я не видел чтобы это было плохой практикой, можно ссылочку на какую-нибудь статью почитать?

**Comment by Fr0stmourne** [comment]
Проблема в том, что такие величины труднее поддерживать и неочевидно, почему там именно 81, а не 84, скажем. Или, если у тебя поменяется отступ, то надо будет снова подгонять эти проценты, чтобы ровно стояло. Пару медиавыражений будет поддерживать проще с большой долей вероятности
