### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by a-poluhin** [sodiqit/fsd-step-2#9]
Небольшая проблемка у сборки. Связана с захардкоженым ip. По идее можно обойтись без хардкода ip.
![image](https://user-images.githubusercontent.com/10168007/92136163-e4f28d80-ee35-11ea-9d00-820cf3b6e107.png)

Еще ошибки:)
![image](https://user-images.githubusercontent.com/10168007/92137012-e8d2df80-ee36-11ea-8ce8-c4d2f624b105.png)

**Comment by sodiqit** [comment]
Да, верно, забыл исправить ip. Сделал это для того чтобы можно было смотреть сайт одновременно на мобильных устройствах. Больше ошибок у меня не возникало. Только что попробовал склонировать проект в новую чистую папку, запустил 
```
npm i
npm start
```
и все работает, запускает локальный сервер
